name: Check Lua Formatting

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check .
          token: ${{ secrets.GITHUB_TOKEN }}
